yarnPath: .yarn/releases/yarn-4.5.1.cjs

httpTimeout: 300000
nodeLinker: node-modules
npmRegistryServer: 'https://registry.npmjs.org/'
npmScopes:
    vizplatform:
        npmAlwaysAuth: true
        npmPublishRegistry: https://registry.vizplatform.nettricity.cloud/
        npmRegistryServer: https://registry.vizplatform.nettricity.cloud/
